apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: # deployment labels
    app: myapp
spec:
  replicas: "{{ .Values.deployment.replicaCount }}"
  selector:
    matchLabels:  # these labels shpuld match with pod labels
      app: nginx
      project: roboshop
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend
    spec:
      containers:
      - name: nginx
        image: "nginx.{{ .Values.deployment.imageVersion }}"
        ports:
        - containerPort: 80
